In [ ]:
Day 15: Classification with Logistic Regression
Introduction to classification problems
Binary classification using logistic regression.
Performance metrics: Accuracy, Precision, Recall, F1-Score

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# load dataset
data = sns.load_dataset('titanic')
data.head(2)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False

In [ ]:
# age , fare and survived
data = data[['survived', 'age', 'fare']]

In [ ]:
# clean the data
data.isna().sum()

survived      0
age         177
fare          0
dtype: int64

In [ ]:
data = data.dropna()
data.isna().sum()

survived    0
age         0
fare        0
dtype: int64

In [ ]:
# Split into X and y
X= data[['age', 'fare']]
y= data['survived']

In [ ]:
# Train the model
from sklearn.linear_model   import LogisticRegression

In [ ]:
model = LogisticRegression()

In [ ]:
# train the model
model.fit(X,y)

LogisticRegression()

In [ ]:
# Predict the values
y_pred = model.predict(X)
y_pred[0:5]

array([0, 1, 0, 0, 0])

In [ ]:
# Performance metrics: Accuracy, Precision, Recall, F1-Score.

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, f1_score, precision_score

In [ ]:
# Confusion matrix

In [ ]:
cm = confusion_matrix(y, y_pred)
cm

array([[380,  44],
       [201,  89]])

In [ ]:
# precision
pres = precision_score(y, y_pred)

In [ ]:
print(f"Precision Score: {pres}")

Precision Score: 0.6691729323308271


In [ ]:
# recall score
rec = recall_score(y, y_pred)
print(f"Recall Score : {rec}")

Recall Score : 0.30689655172413793


In [ ]:
# f1 Score
f1_sco = f1_score(y, y_pred)
print(f"F1 Score :{f1_sco}")

F1 Score :0.42080378250591016


In [ ]:
# Multiplie (Multi) Classfication

In [ ]:
data_peng = sns.load_dataset('penguins')

In [ ]:
data_peng.shape

(344, 7)

In [ ]:
data_peng.head(2)

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female

In [ ]:
data_peng.drop(['island','sex'], axis=1,inplace=True)

In [ ]:
data_peng.isna().sum()

species              0
bill_length_mm       2
bill_depth_mm        2
flipper_length_mm    2
body_mass_g          2
dtype: int64

In [ ]:
data_peng = data_peng.dropna()

In [ ]:
data_peng.isna().sum()

species              0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
dtype: int64

In [ ]:
X = data_peng.drop('species', axis=1)
X.head(2)

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
0            39.1           18.7              181.0       3750.0
1            39.5           17.4              186.0       3800.0

In [ ]:
y = data_peng['species']
y.head(2)

0    Adelie
1    Adelie
Name: species, dtype: object

In [ ]:
lr = LogisticRegression(max_iter =1000)
lr

LogisticRegression(max_iter=1000)

In [ ]:
# fit the model
lr.fit(X,y)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=1000)

In [ ]:
y_pred = lr.predict(X)

In [ ]:
y_pred[0:5]

array(['Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie'], dtype=object)

In [ ]:
# Project Mobile Fone Price Prediction
import ipywidgets as widgets
from IPython.display import display

In [ ]:
upload_widget = widgets.FileUpload(
    accept='.csv',   # only CSV files
    multiple=False   # single file upload
)

display(upload_widget)

FileUpload(value={}, accept='.csv', description='Upload')

In [ ]:
# function to read csv file
def load_csv_from_widget(upload_widget):
    if len(upload_widget.value) == 0:
        print("No file uploaded.")
        return None

    uploaded_file = list(upload_widget.value.values())[0]

    # Convert bytes → file-like object
    csv_bytes = uploaded_file['content']
    csv_buffer = io.BytesIO(csv_bytes)

    df = pd.read_csv(csv_buffer)
    return df


In [ ]:
import io

In [ ]:
df = load_csv_from_widget(upload_widget)
df

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

In [ ]:
data = df.copy()

In [ ]:
data.columns

Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi', 'price_range'],
      dtype='object')

In [ ]:
data['price_range'].unique()

array([1, 2, 3, 0])

In [ ]:
# Logisictic Regression
# check na
data.isna().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [ ]:
# Split data in to X and y

In [ ]:
X = data.drop('price_range', axis=1)

In [ ]:
y = data['price_range']

In [ ]:
X.shape

(2000, 20)

In [ ]:
# binary (0,1)
# multpler (0,1,.....)
data['price_range'].unique()

array([1, 2, 3, 0])

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model = LogisticRegression()

In [ ]:
# Fit (train) the model

In [ ]:
model.fit(X,y)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
# Predict the values
y_pred = model.predict(X)

In [ ]:
y_pred[0:5]

array([1, 2, 2, 3, 1])

In [ ]:
# Accuracy_score, f1_score
from sklearn.metrics import accuracy_score , f1_score

In [ ]:
acs = accuracy_score(y, y_pred)
acs

0.6355

In [ ]:
# f1Sore
f_score = f1_score(y,y_pred)

ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].

In [ ]:
 act   pradi
0 1
1 1
1 1
2 2
3 3
1 1
0 0
1 1
9/ 10
90%

In [ ]:
micro macro
Multiple Classfication
0
1
2
3...
True [1] (postive, negative)
False [0] (postive , negative)